global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aiops-cluster'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load alert rules
rule_files:
  - '/etc/prometheus/alert_rules.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          environment: 'production'

  # AIOps Processor
  - job_name: 'aiops-processor'
    static_configs:
      - targets: ['aiops-processor:8000']
        labels:
          service: 'aiops-processor'
          environment: 'production'

  # Ollama
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
        labels:
          service: 'ollama'
          environment: 'production'


